apiVersion: v1
kind: Pod
metadata:
  name: arush-pi-test
spec:
  containers:
  - name: arush-pi-test
    image: perl:5.34.0
    command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
    resources:
      limits:
        memory: 500Mi
        cpu: 500m
      requests:
        memory: 100Mi
        cpu: 50m
  restartPolicy: Never